#dynamic prog for accepting two values from kbd
print("Enter First Value:")
a=input()
print("Enter Second Value:")
b=input()
c=int(a)+int(b)
print("-"*90)
print("val of a=",a)
print("val of b=",b)
print("sum=",c)
print("-"*90)
