#info.py
fp=open("info.data")
print("Init pos of fp=",fp.tell())
data=fp.read(6)
print("data after read=",data)
print("pos of fp after read=",fp.tell())
fp.seek(8)
print("pos of fp after seek=",fp.tell())
data=fp.read(4)
print(data)
print("pos of fp after read=",fp.tell())
fp.seek(0)
print("pos of fp after seek=",fp.tell())
data=fp.read()
print(data)
